### ISSUE TITLE
Freeze when touching touchpad

### ISSUE THREAD

**Issue by agrytnes** [vlasenko/hid-asus-dkms#4] opened 2016-11-16 23:40 UTC
After install I had to reboot a few times to be able to log in. It might have been that I touched the pad while loading Ubuntu. Now everything works fine until I touch the pad. When I do the PC freeze and caps look is blinking.

**Comment by redmcg** [comment] 2016-11-17 01:26
@agrytnes Before it freezes (and after it has booted) can you please send the output of:
`dmesg | grep hid`

You also might want to try the userspace driver (which can be found [here](https://github.com/redmcg/FTE1001)).

Make sure the hid_asus_fte module is not loaded when using the userspace driver. The hid_generic module should be loaded instead.

**Comment by agrytnes** [comment] 2016-11-17 06:31
This is output of dmesg | grep hid
![image](https://cloud.githubusercontent.com/assets/23460540/20378600/68b5b92e-ac97-11e6-8937-a3bce079caf7.png)

![image](https://cloud.githubusercontent.com/assets/23460540/20378473/abbec2d4-ac96-11e6-90ca-b8f758355513.png)

**Comment by larixer** [comment] 2016-11-17 06:44
@agrytnes Please make sure this issue is happening on the latest driver source code.

https://github.com/vlasenko/hid-asus-fte-dkms#updating-to-the-latest-driver-version

**Comment by agrytnes** [comment] 2016-11-17 07:16
After latest driver source code ubuntu is no longer freezing and output looks different.

![image](https://cloud.githubusercontent.com/assets/23460540/20379724/1c85969e-ac9e-11e6-8012-7a3374870b12.png)

**Comment by larixer** [comment] 2016-11-17 07:44
Yes, the driver is not loaded now, however. I bet you don't have two finger scroll working now

**Comment by agrytnes** [comment] 2016-11-17 07:56
No two finger scrolling is correct. The only change is that the mouse cursor looks different and it changes to a pointing hand when over a link.

**Comment by larixer** [comment] 2016-11-17 07:57
If two finger scroll is not working, try the following sequence please:
1. Comment out MODULES_CONF line and REMAKE_INITRD line with prepending # in hid-asus-fte-dkms/dkms.conf
2. Run `./dkms-add.sh`
3. Add the following line to the end of `/etc/initramfs-tools/modules`:
  `hid_asus_fte`
4. Update initrd:
  `sudo update-initramfs -u`
5. Reboot

**Comment by larixer** [comment] 2016-11-17 08:15
> No two finger scrolling is correct. The only change is that the mouse cursor looks different and it changes to a pointing hand when over a link.

I'm confused. According to the last your dmesg there is no `hid-focaltech` string in your logs, and only `hid-generic`. This means that the kernel is using it's stock driver for this touchpad. However, if you additionally run userspace driver from here: https://github.com/redmcg/FTE1001, then TouchPad will be handled by userspace driver. Please note that you should use either this DKMS driver or userspace one, not both. Please confirm that you are not using userspace driver and that your logs don't have `hid-focaltech` string and two finger scrolling works.

**Comment by agrytnes** [comment] 2016-11-17 08:35
Iv done 1. and 2. but im not sure what to do in 3. 

Im quite new to linux so im not sure where to look for FTE1001. I did clone it from github and i find the folder but i did not think I installed anything. How do I uninstall FTE1001 if i have it?

Thank you for your patience
Andreas

**Comment by larixer** [comment] 2016-11-17 08:51
@agrytnes I think you need to do 1-5 if you don't have two finger scroll working. If you do have it working, no need to do this. Please uncoment MODULES_CONF and REMAKE_INITRD lines again and run ./dkms-add

If you didn't install FTE1001 you would have known how to uninstall it, so no need to uninstall it. Simply cloning FTE1001 won't install anything.

**Comment by larixer** [comment] 2016-11-17 10:09
@agrytnes Let us know if TouchPad is working for you and we can close this issue

**Comment by agrytnes** [comment] 2016-11-17 11:25
Im working on step 4.

geting output:
![image](https://cloud.githubusercontent.com/assets/23460540/20387544/e82b23aa-acc0-11e6-9a1a-df6fef3e8a3d.png)

**Comment by redmcg** [comment] 2016-11-17 20:42
They're just warnings and unrelated to this driver. You can ignore that. But that does mean you've completed step 4.

You can confirm the driver is in now your initrd by running:
`lsinitramfs /boot/initrd.img-`uname -r`| grep asus`

You should see output similar to:
`lib/modules/4.4.0-47-generic/updates/dkms/hid-asus-fte.ko`

If so the driver should now work after a reboot. If it isn't working - please run `dmesg | grep hid` again and provide the output.

**Comment by agrytnes** [comment] 2016-11-17 21:22
iv done step 1-5 and the touchpad is stil not working.

lsinitramfs /boot/initrd.img-uname -r | grep asus 
only gave:
/usr/bin/lsinitramfs: invalid option -- 'r'

dmesg | grep hid:
![image](https://cloud.githubusercontent.com/assets/23460540/20407878/7b71e0fc-ad13-11e6-8f67-4058de260d5e.png)

**Comment by redmcg** [comment] 2016-11-17 21:27
Sorry - that's my fault. I used a back tick in the command and Git uses that as a formatting character so it was removed. Run this instead:
`lsinitramfs /boot/initrd.img-$(uname -r) | grep asus`

The dmesg shows that the new driver is not being loaded. Can you try running:
`sudo modprobe hid_asus_fte`

and let me know the output?

**Comment by agrytnes** [comment] 2016-11-17 21:31
No worries! Im just happy to get help.

![image](https://cloud.githubusercontent.com/assets/23460540/20408369/79db1c3e-ad15-11e6-99d4-a8a0c1e062f9.png)

**Comment by agrytnes** [comment] 2016-11-17 21:32
![image](https://cloud.githubusercontent.com/assets/23460540/20408433/b935e4c2-ad15-11e6-8fb3-adcf1214dd04.png)

**Comment by redmcg** [comment] 2016-11-17 21:39
OK - I think I know what the issue is now. It looks like you're using secure boot - and because our module isn't officially in the linux repos (i.e. it is considered third party) - it is being rejected.

You'll either need to disable secure boot or use the [userspace driver](https://github.com/redmcg/FTE1001).

The userspace driver is a program you run that talks to the device via useful interfaces provided by the kernel (`hidraw` and `uinput`). If you want to use the userspace driver I'll close this issue and we can open a new one in the [FTE1001 repo](https://github.com/redmcg/FTE1001) if required.

**Comment by agrytnes** [comment] 2016-11-17 21:44
I will try disable secure boot

**Comment by agrytnes** [comment] 2016-11-17 21:55
You were right! It works perfectly now! Big thanks to you and Victor!

**Closed as completed** 2016-11-17 21:56 UTC
